/**
 * 12-phase AI fraud stack — copy used in FraudShield hero showcase.
 * Phase numbers match backend risk-engine documentation.
 */
export const FRAUD_SHIELD_PHASES = [
  {
    n: 1,
    key: "events",
    name: "Event Engine",
    blurb: "Real-time transaction event bus",
    hoverDetail: "Ingesting 18.4k events/hour · sub-50ms fan-out to scoring DAG",
    icon: "Zap",
  },
  {
    n: 2,
    key: "features",
    name: "Feature Store",
    blurb: "200+ behavioural signals computed live",
    hoverDetail: "212 signals materialised · Redis online + offline snapshots warm",
    icon: "Layers",
  },
  {
    n: 3,
    key: "xgb",
    name: "Supervised Learning",
    blurb: "XGBoost trained on fraud labels",
    hoverDetail: "Model v4.2 · PR-AUC 0.91 on last holdout · calibration checked daily",
    icon: "LineChart",
  },
  {
    n: 4,
    key: "policies",
    name: "Decision Engine",
    blurb: "Per-merchant risk policies",
    hoverDetail: "847 active merchant policies · blacklist sync < 2 min",
    icon: "Shield",
  },
  {
    n: 5,
    key: "mlops",
    name: "MLOps & Registry",
    blurb: "Drift detection + auto-retrain",
    hoverDetail: "PSI watch on 14 features · last retrain 3d ago · canary healthy",
    icon: "Activity",
  },
  {
    n: 6,
    key: "graph",
    name: "Graph Intelligence",
    blurb: "Fraud ring & mule detection",
    hoverDetail: "Graph expander pruned 2.1M edges · 6 high-risk clusters flagged today",
    icon: "GitBranch",
  },
  {
    n: 7,
    key: "shap",
    name: "SHAP Explainability",
    blurb: "Why was this flagged?",
    hoverDetail: "Phase 7 — SHAP — running on 1,247 transactions today",
    icon: "Sparkles",
  },
  {
    n: 8,
    key: "feedback",
    name: "Feedback Flywheel",
    blurb: "Analyst labels → retraining",
    hoverDetail: "312 labels this week · queue SLA 4h median",
    icon: "RefreshCw",
  },
  {
    n: 9,
    key: "llm",
    name: "LLM Investigation Agent",
    blurb: "Agentic AI auto-investigates",
    hoverDetail: "Agent budget 92% utilised · 41 deep dives completed today",
    icon: "Search",
  },
  {
    n: 10,
    key: "gnn",
    name: "Graph Neural Network",
    blurb: "GraphSAGE user embeddings",
    hoverDetail: "64-dim embeddings refreshed · serving latency p99 38ms",
    icon: "Network",
  },
  {
    n: 11,
    key: "dnn",
    name: "DNN Shadow",
    blurb: "Deep neural net running in shadow",
    hoverDetail: "Shadow traffic 12% · blend weight 0.18 · no promotion pending",
    icon: "Cpu",
  },
  {
    n: 12,
    key: "orch",
    name: "Orchestrator",
    blurb: "Intelligent model routing & cost optimization",
    hoverDetail: "Tier routing saved 27% LLM calls vs baseline this week",
    icon: "Workflow",
  },
];
