-- Seven internal ghost users for signup bank-link demo (transactions generated by app).
-- Pool IDs 900001–900007 — see services/signup_bank_ghost_pool.py

INSERT INTO users (
  id, email, password_hash, name, monthly_income, bank, city,
  onboarding_completed, is_verified
)
OVERRIDING SYSTEM VALUE
VALUES
  (900001, 'signup_ghost_hdfc@pool.smartspend.internal', '$2a$10$disabled',
   'Arjun Patel', 52000, 'HDFC', 'Hyderabad', TRUE, FALSE),
  (900002, 'signup_ghost_sbi@pool.smartspend.internal', '$2a$10$disabled',
   'Priya Nair', 48000, 'SBI', 'Kochi', TRUE, FALSE),
  (900003, 'signup_ghost_icici@pool.smartspend.internal', '$2a$10$disabled',
   'Kavya Reddy', 88000, 'ICICI', 'Kolkata', TRUE, FALSE),
  (900004, 'signup_ghost_axis@pool.smartspend.internal', '$2a$10$disabled',
   'Rohan Mehta', 62000, 'AXIS', 'Ahmedabad', TRUE, FALSE),
  (900005, 'signup_ghost_kotak@pool.smartspend.internal', '$2a$10$disabled',
   'Siddharth Joshi', 55000, 'KOTAK', 'Lucknow', TRUE, FALSE),
  (900006, 'signup_ghost_pnb@pool.smartspend.internal', '$2a$10$disabled',
   'Neha Gupta', 28000, 'PNB', 'Jaipur', TRUE, FALSE),
  (900007, 'signup_ghost_bob@pool.smartspend.internal', '$2a$10$disabled',
   'Amit Desai', 72000, 'BOB', 'Surat', TRUE, FALSE)
ON CONFLICT (id) DO NOTHING;

-- Run once after deploy to materialize transactions:
--   python backend/scripts/seed_signup_bank_ghost_pool.py
